### ISSUE TITLE
New Features of this linter

### ISSUE THREAD

**Issue by manuelarte** [manuelarte/embeddedstructfieldcheck#10]
This linter is based on the Uber style guide described in [Embedding In Structs](https://github.com/uber-go/guide/blob/master/style.md#embedding-in-structs), but there are more styles/rules regarding embedding types described.

# Avoid Embedding Types in Public Structs
Described [here](https://github.com/uber-go/guide/blob/master/style.md#embedding-in-structs), as a summary:

```
An embedded type is rarely necessary. It is a convenience that helps you avoid writing tedious delegate methods.
```

What do you think of adding an option that checks this?

# Mutexes should not be embedded, even on unexported types

In the Uber Style is described that mutexes should not be embedded at all. I personally like this check.

What do you think of adding this check?

Cheers.

**Comment by manuelarte** [comment]
@ldez completely agree with you. Then I will work in the second point, adding it as an option like:

```
settings:
    embeddedstructfieldcheck:
      # Checks that sync.Mutex is not used as an embedded field.
      # Default: false
      nomutex: true
```

any comments about the naming, etc?
